# Generated by Django 4.0.3 on 2024-01-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('birth_date', models.DateField()),
                ('last_login', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(upload_to='profile_pics/')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_slug', models.SlugField()),
                ('personal_website', models.URLField()),
            ],
        ),
    ]
